# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER:-tiagomarquespereira}
      - DB_PASS=${DB_PASS:-}
      - DB_NAME=${DB_NAME:-crypto_db}
    depends_on:
      - db
    command: ["python", "etl.py"]

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-tiagomarquespereira}
      POSTGRES_PASSWORD: ${DB_PASS:-}
      POSTGRES_DB: ${DB_NAME:-crypto_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: